// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package eshopsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Address struct {
	ID           int64
	AddressLine1 pgtype.Text
	AddressLine2 pgtype.Text
	City         pgtype.Text
	PostCode     pgtype.Int8
	Country      pgtype.Text
	UserID       pgtype.Int8
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type User struct {
	ID        int64
	FirstName pgtype.Text
	LastName  pgtype.Text
	Email     string
	Phone     pgtype.Text
	Password  pgtype.Text
	Code      pgtype.Text
	Expiry    pgtype.Timestamptz
	Verified  pgtype.Bool
	UserType  pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
