// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package eshopsqlc

import (
	"context"
)

const getuser = `-- name: Getuser :one
SELECT id, first_name, last_name, email, phone, password, code, expiry, verified, user_type, created_at, updated_at FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) Getuser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getuser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.Code,
		&i.Expiry,
		&i.Verified,
		&i.UserType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
